version: '3'
services:
  odoo:
    build:
      context: https://github.com/computerservice-mog/Odoo.git
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - data:/var/lib/odoo  # Persistent storage for Odoo data
      - ./addons:/mnt/extra-addons  # Mount custom addons directory (if applicable)
      - ./config:/etc/odoo  # Mount custom Odoo configuration (if applicable)
 
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata  # Persistent storage for PostgreSQL data
 
volumes:
  data:
  db:

